Modifying the pipeline

diff --git a/.github/workflows/ci_cd_pipeline.yaml b/.github/workflows/ci_cd_pipeline.yaml
--- a/.github/workflows/ci_cd_pipeline.yaml
+++ b/.github/workflows/ci_cd_pipeline.yaml
@@ -135,4 +135,12 @@ jobs:
         run: pip install cyclonedx-bom
 
       - name: Generate SBOM
-        run: cyclonedx-py requirements -o bom.json
+        run: |
+          ls -la  # List files to check if requirements.txt exists
+          cyclonedx-py requirements -o bom.json || echo "SBOM generation failed"
+
+      - name: Upload SBOM as Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: sbom
+          path: bom.json  # or path to a folder like ./output/bom.json
